language: java

jdk:
  - oraclejdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "YeOHV8VQtBfwuKQx1pC+nktCzc/fhz6PsKYCVyXAuOYGxf72Utg0aETRyg97vwWYrceBl+fOFAxgn2zNOlI/gEi4zau7kZMDycXHiVByw1yr+bpP4VafKXSRh5YRdWunOqmj5qXEFi4uOoNNUVn1zvlC5dk7xTAXF4xzFVsCs3w="

addons:
  coverity_scan:
    project:
      name: "bkimminich/kata-tcg"
      description: "Kata TCG build submitted via Travis CI"
    notification_email: bjoern.kimminich@gmx.de
    build_command_prepend: "gradle clean"
    build_command: "gradle assemble"
    branch_pattern: coverity_scan

after_success:
  gradle jacocoTestReport coveralls