language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

env:
  global:
   - secure: "YeOHV8VQtBfwuKQx1pC+nktCzc/fhz6PsKYCVyXAuOYGxf72Utg0aETRyg97vwWYrceBl+fOFAxgn2zNOlI/gEi4zau7kZMDycXHiVByw1yr+bpP4VafKXSRh5YRdWunOqmj5qXEFi4uOoNNUVn1zvlC5dk7xTAXF4xzFVsCs3w="

addons:
  coverity_scan:
    project:
      name: "bkimminich/kata-tcg"
      description: "Kata TCG build submitted via Travis CI"
    notification_email: bjoern.kimminich@gmx.de
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew assemble"
    branch_pattern: coverity_scan
  code_climate:
    repo_token: 45e3b73d13d7e754ba200dc6a60ca8eaff54f8e7a800d78a7b085d63d4f1e533

after_success:
  ./gradlew jacocoTestReport coveralls
  ./tcg-js/node_modules/.bin/lcov-result-merger 'tcg-js/coverage/*/lcov.info' 'tcg-js/coverage/lcov_merged.info'
  cat "./tcg-js/coverage/lcov_merged.info" | ./node_modules/.bin/codeclimate
